name: Docker security checks

on:
  workflow_call:
    inputs:
      image-tag:
        description: Tag of Docker image (without repository) to verify
        required: true
        type: string
      working-directory:
        description: Workflow working directory
        default: '.'
        required: false
        type: string
    secrets:
      REGISTRY:
        description: The registry where the image will be pulled from.
        required: true
      ECR_AWS_ACCESS_KEY_ID:
        description: An AWS access key ID that has read permissions to the registry.
        required: true
      ECR_AWS_SECRET_ACCESS_KEY:
        description: An AWS secret access key that has read permissions to the registry.
        required: true
      ECR_AWS_REGION:
        description: AWS region for the registry.
        required: true

jobs:
  sast:
    name: Docker SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SAST
        uses: equisoft-actions/docker-sast@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ECR_AWS_REGION }}
          image-name: ${{ secrets.REGISTRY }}/${{ inputs.image-tag }}
          working-directory: ${{ inputs.working-directory }}

  sbom:
    name: Docker SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate and publish SBOM
        uses: equisoft-actions/docker-sbom@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ECR_AWS_REGION }}
          image-name: ${{ secrets.REGISTRY }}/${{ inputs.image-tag }}
          publish: ${{ inputs.dependency-track-publish }}
          working-directory: ${{ inputs.working-directory }}
